name: medicalrecordsystem

on:
  push:
    branches:
      - master
    pull_request:
      branches:
        - master
jobs:
  builds:
    runs-on: windows

    services:
      mysql:
        image: mysql:latest
        env:
          MySQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: userRegister

